--
-- PostgreSQL database dump
--

\restrict LxZuOpY2afite4hUNknKCXdUYhTgJAUhRpEc01htX7YZbHiaA1DbcRjPFmVS4PH

-- Dumped from database version 17.10 (322a063)
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    address character varying(255),
    credit_age_months integer,
    credit_score integer,
    credit_utilization_ratio double precision,
    debt_to_income_ratio double precision,
    email character varying(255),
    emi double precision,
    income double precision,
    name character varying(255),
    number_of_accounts integer,
    password character varying(255),
    payment_history_score integer,
    phone character varying(255),
    role character varying(255)
);


--
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.emi (
    id bigint NOT NULL,
    amount double precision,
    due_date date,
    emi_number integer,
    payment_date timestamp(6) without time zone,
    payment_method character varying(255),
    status character varying(255),
    loan_id bigint NOT NULL,
    CONSTRAINT emi_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'OVERDUE'::character varying])::text[])))
);


--
-- Name: emi_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.emi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.loan (
    id bigint NOT NULL,
    admin_comments character varying(255),
    amount double precision,
    application_date timestamp(6) without time zone,
    approval_date timestamp(6) without time zone,
    emi_amount double precision,
    interest_rate double precision,
    purpose character varying(255),
    status character varying(255),
    tenure integer,
    total_amount double precision,
    customer_id bigint NOT NULL,
    CONSTRAINT loan_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: loan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.customer (id, address, credit_age_months, credit_score, credit_utilization_ratio, debt_to_income_ratio, email, emi, income, name, number_of_accounts, password, payment_history_score, phone, role) FROM stdin;
\.


--
-- Data for Name: emi; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.emi (id, amount, due_date, emi_number, payment_date, payment_method, status, loan_id) FROM stdin;
\.


--
-- Data for Name: loan; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.loan (id, admin_comments, amount, application_date, approval_date, emi_amount, interest_rate, purpose, status, tenure, total_amount, customer_id) FROM stdin;
\.


--
-- Name: customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.customer_id_seq', 1, true);


--
-- Name: emi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.emi_id_seq', 1, false);


--
-- Name: loan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.loan_id_seq', 1, true);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- Name: emi emi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emi
    ADD CONSTRAINT emi_pkey PRIMARY KEY (id);


--
-- Name: loan loan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT loan_pkey PRIMARY KEY (id);


--
-- Name: emi fk2lfrfgr2iu0xm655ipg153jy4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.emi
    ADD CONSTRAINT fk2lfrfgr2iu0xm655ipg153jy4 FOREIGN KEY (loan_id) REFERENCES public.loan(id);


--
-- Name: loan fkcwv05agfqwg5ndy6adbefsx7d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fkcwv05agfqwg5ndy6adbefsx7d FOREIGN KEY (customer_id) REFERENCES public.customer(id);


--
-- PostgreSQL database dump complete
--

\unrestrict LxZuOpY2afite4hUNknKCXdUYhTgJAUhRpEc01htX7YZbHiaA1DbcRjPFmVS4PH

