services:
  - type: web
    name: credit-score-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/credit-scores/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JAVA_OPTS
        value: -Xmx256m -Xms128m -XX:+UseSerialGC -Xss256k -XX:MaxMetaspaceSize=96m -XX:ReservedCodeCacheSize=64m -XX:TieredStopAtLevel=1 -XX:+UseCompressedOops -Djava.security.egd=file:/dev/./urandom
